# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SpringBoot CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: docker.io
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          
      - name: Building and Pushing user-service
        run: mvn package dockerfile:push --file pizza-ms-msa-order-backend/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Deploy to EKS cluster
        uses: Azure/aks-set-context@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          creds: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: order-service-app
          cluster-name: demo-cluster-1
          region: us-west-1
          
      - name: Deploy to EKS cluster  
        uses: Azure/k8s-deploy@v1
        with:
         manifests: |
          k8s/deployment.yaml
          
      - name: Run Kube-Bench to check cluster config
        continue-on-error: true
        run: |
         kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/main/job-aks.yaml
         sleep 30s
         kubectl logs job.batch/kube-bench
         kubectl delete job.batch/kube-bench
       
        
   
 
          
      
        
     
  
